# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Damien's Daimon
tagline:          ''
description:      'Content with nothing to sell and no promise of coherence.'
url:              
baseurl:          /

author:
  name:           'Damo'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
